name: Cowsay-Draw

on:
    push:
        branches:
            - "main"
        paths:
            - ".github/workflows/cowsay.yml"
    workflow_dispatch:

jobs:
    cowsay-draw:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: List Files
              run: ls -ltra

            - name: Run Shell Script
              run: |
                  chmod +x myscript.sh
                  ./myscript.sh
