name: First Workflow

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/first.yml"

jobs:
  firstjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a multi-line cmds
        run: |
          echo "Hello, Github Class for GH-200!"
          ls -ltra
          cat README.md

      #- name: Cowsay Drawing
      #  run: cowsay -f dragon "I am a dragon! FIRE FIRE!!!"  >> dragon.txt

      #- name: List files
      #  run: ls -la

      #- name: Read file
      #  run: cat README.md
